<?php

namespace Grossum\ContactBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactToEmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactToEmailRepository extends EntityRepository
{
}
