<?php

namespace Grossum\ContactBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository
{
    public function findAllEnabled()
    {
        $query = $this->createQueryBuilder('contact');

        $query
            ->leftJoin('contact.phone', 'phone', 'WITH', 'phone.enabled = :enabled')
            ->addSelect('phone')
            ->leftJoin('contact.email', 'email', 'WITH', 'email.enabled = :enabled')
            ->addSelect('email')
            ->where('contact.enabled = :enabled')
            ->setParameter('enabled', true);

        return $query->getQuery()->getResult();
    }
}
